# Generated by Django 4.2.27 on 2026-03-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_company_user_is_super_admin_and_more'),
        ('remote_support', '0003_remotesupportsession_is_voice_active_voicetranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesupportsession',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to='cmdb.company'),
        ),
    ]
