# Generated by Django 4.2.27 on 2026-02-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_twofactordevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('phone', 'Phone'), ('printer', 'Printer'), ('network', 'Network Equipment'), ('software', 'Software License'), ('other', 'Other')], max_length=20),
        ),
    ]
