# Generated by Django 4.2.27 on 2026-02-09 14:47

from django.db import migrations

def load_initial_data(apps, schema_editor):
    """Load initial knowledge base data using migration-safe approach."""
    Category = apps.get_model('knowledge', 'Category')
    
    categories = [
        {'name': 'Hardware', 'description': 'Hardware troubleshooting and guides', 'icon': 'bi-laptop', 'order': 1},
        {'name': 'Software', 'description': 'Software installation and usage', 'icon': 'bi-code-square', 'order': 2},
        {'name': 'Network', 'description': 'Network connectivity and VPN', 'icon': 'bi-wifi', 'order': 3},
        {'name': 'Security', 'description': 'Security policies and best practices', 'icon': 'bi-shield-lock', 'order': 4},
    ]
    
    for cat_data in categories:
        Category.objects.get_or_create(name=cat_data['name'], defaults=cat_data)

def reverse_load(apps, schema_editor):
    pass  # Don't delete on reverse

class Migration(migrations.Migration):
    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_load),
    ]
