# Generated by Django 4.2.27 on 2026-02-09 14:47

from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial_kb_data.json')

class Migration(migrations.Migration):
    atomic = False  # loaddata requires running outside atomic transaction

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
