# Generated by Django 4.2.27 on 2026-03-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_company_user_is_super_admin_and_more'),
        ('service_requests', '0003_servicerequest_allocated_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='cmdb.company'),
        ),
    ]
